name: Update Documentation
on:
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
jobs:
  update-docs-label:
    name: Update via Label
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.label.name == 'update-docs'
    permissions:
      contents: write
      pull-requests: write
      actions: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install pyyaml
      
      - name: Update documentation
        id: update
        run: |
          set -e
          python tools/doc-generator.py
          
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            git add -A
            git commit -m "docs: update documentation"
            git push origin HEAD
            
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Trigger check workflow
        if: steps.update.outputs.updated == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Wait a moment for the push to be processed
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            // Trigger a new check run
            await github.rest.checks.create({
              ...context.repo,
              name: 'Verify Documentation',
              head_sha: '${{ steps.update.outputs.commit_sha }}',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Documentation is up to date',
                summary: '✅ Documentation was automatically updated and verified'
              }
            });
            
            // Trigger check re-run
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: context.issue.number,
              reviewers: []
            }).catch(() => {});
      
      - name: Remove label and update comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            // Remove the label
            await github.rest.issues.removeLabel({
              ...context.repo,
              issue_number: context.issue.number,
              name: 'update-docs'
            }).catch(() => {});
            
            // Prepare the status message
            const updated = '${{ steps.update.outputs.updated }}' === 'true';
            const body = updated
              ? '## 📚 Documentation Status: Updated\n\n✅ Documentation has been successfully updated and verified!'
              : '## 📚 Documentation Status: Current\n\n✅ Documentation was already up to date.';
            
            // Find existing bot comment
            const comments = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.data.find(c => 
              c.user.type === 'Bot' && c.body.includes('📚 Documentation Status:')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                ...context.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment if none exists (edge case)
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
